---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default
  namespace: traefik-system
spec:
  secretName: default
  dnsNames:
    - "app.rick.expresso.lan"
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
