---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- tls-store.yaml
- certificate.yaml

secretGenerator:
- name: traefik-values
  namespace: kube-system
  files:
  - values=values.yaml
  options:
    disableNameSuffixHash: true
