---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service/web-svc-service.yaml
- certificate/web-svc-certificate.yaml
- ingressroute/web-svc-ingressroute.yaml
- middleware/web-svc-headers-middleware.yaml
- pvc/cache-pvc.yaml
- pvc/plugins-pvc.yaml
- pvc/config-pvc.yaml
- pvc/data-pvc.yaml
- pvc/images-pvc.yaml
- pvc/media-pvc.yaml
- pvc/metadata-pvc.yaml
- pvc/transcodes-pvc.yaml
