---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- middleware/headers.yaml
- pvc/cache-pvc.yaml
- pvc/plugins-pvc.yaml
- pvc/config-pvc.yaml
- pvc/data-pvc.yaml
- pvc/images-pvc.yaml
- pvc/media-pvc.yaml
- pvc/metadata-pvc.yaml
- pvc/transcodes-pvc.yaml