---
resources:
- namespace.yaml
- deployment.yaml
- pvc/media-pvc.yaml

configMapGenerator:
  - name: motion-conf-cm
    namespace: motion
    files:
      - configmap/motion.conf
    options:
      disableNameSuffixHash: true
