---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rtsp0-hls-ingressroute
  namespace: v4l2rtspserver
spec:
  entryPoints:
    - websecure
  routes:
  - match: Path(`/rtsp0`)
    kind: Rule
    priority: 30
    services:
    - kind: Service
      name: rtsp0-hls-svc
      namespace: v4l2rtspserver
      passHostHeader: true
      port: hls-web
      responseForwarding:
        flushInterval: 1ms
      scheme: http
      sticky:
        cookie:
          httpOnly: true
          name: cookie
          secure: true
          sameSite: none
          maxAge: 42  
      weight: 40
      nativeLB: false
      nodePortLB: true
  tls: {}
