---
resources:
- ../../base
- ingressroute/rtsp0-hls-ingressroute.yaml

patches:
  - path: deployment.yaml

secretGenerator:
- name: rtsp0-password
  namespace: v4l2rtspserver
  files:
  - rtsp0.password.txt
  options:
    disableNameSuffixHash: true
