---
resources:
- ../../base
- servers_transport/servers-transport-tcp.yaml
- ingressroutes/ingressroute-rtsp-hls.yaml
- ingressroutes/ingressroute-rtsp-tcp.yaml
- ingressroutes/ingressroute-rtsp-udp.yaml

patches:
  - path: deployment.yaml

secretGenerator:
- name: rtsp0-password
  namespace: v4l2rtspserver
  files:
  - rtsp0.password.txt
  options:
    disableNameSuffixHash: true
