---
### Create Systemd Instance Symlinks ###
- name: Create symlink for ip-route-add@server.service instance - "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_SERVER.SERVICE }}"
  ansible.builtin.file:
    src: "{{ REMOTE.USR.LIB.SYSTEMD.SYSTEM.FILES.IP_ROUTE_ADD_SERVICE }}"
    dest: "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_SERVER.SERVICE }}"
    owner: root
    group: root
    state: link
  tags:
    systemd.services
    systemd.services.ip-route-add
    systemd.services.ip-route-add.server
    systemd.services.ip-route-add.server.service

- name: Create symlink for ip-route-add@agent-remote.service instance - "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_AGENT_REMOTE.SERVICE }}"
  ansible.builtin.file:
    src: "{{ REMOTE.USR.LIB.SYSTEMD.SYSTEM.FILES.IP_ROUTE_ADD_SERVICE }}"
    dest: "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_AGENT_REMOTE.SERVICE }}"
    owner: root
    group: root
    state: link
  tags:
    systemd.services
    systemd.services.ip-route-add
    systemd.services.ip-route-add.agent-remote
    systemd.services.ip-route-add.agent-remote.service

- name: Create symlink for ip-route-add@cluster.service instance - "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_CLUSTER.SERVICE }}"
  ansible.builtin.file:
    src: "{{ REMOTE.USR.LIB.SYSTEMD.SYSTEM.FILES.IP_ROUTE_ADD_SERVICE }}"
    dest: "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_CLUSTER.SERVICE }}"
    owner: root
    group: root
    state: link
  tags:
    systemd.services
    systemd.services.ip-route-add
    systemd.services.ip-route-add.cluster
    systemd.services.ip-route-add.cluster.service

- name: Create symlink for ip-route-add@vrf10.service instance - "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_VRF10.SERVICE }}"
  ansible.builtin.file:
    src: "{{ REMOTE.USR.LIB.SYSTEMD.SYSTEM.FILES.IP_ROUTE_ADD_SERVICE }}"
    dest: "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_VRF10.SERVICE }}"
    owner: root
    group: root
    state: link
  tags:
    systemd.services
    systemd.services.ip-route-add
    systemd.services.ip-route-add.vrf10
    systemd.services.ip-route-add.vrf10.service

- name: Create symlink for ip-route-add@end0.service instance - "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_END0.SERVICE }}"
  ansible.builtin.file:
    src: "{{ REMOTE.USR.LIB.SYSTEMD.SYSTEM.FILES.IP_ROUTE_ADD_SERVICE }}"
    dest: "{{ REMOTE.ETC.SYSTEMD.SYSTEM.FILES.LINKS.IP_ROUTE_ADD_END0.SERVICE }}"
    owner: root
    group: root
    state: link
  tags:
    systemd.services
    systemd.services.ip-route-add
    systemd.services.ip-route-add.vrf10
    systemd.services.ip-route-add.vrf10.service
