---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-37.1.1+up37.1.0.tgz
  set:
    global.systemDefaultRegistry: ""
  targetNamespace:  traefik-system
  # https://github.com/k3s-io/k3s-charts/blob/main/charts/traefik/37.1.1%2Bup37.1.0/values.yaml
  # https://github.com/k3s-io/k3s-charts/blob/main/charts/traefik/37.1.1%2Bup37.1.0/VALUES.md
  valuesSecrets:
  - name: traefik-values
    ignoreUpdates: false
    keys:
      - values
