---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-plugins-pvc
  namespace: jellyfin
  annotations:
    volumeType: hostPath
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-default
  resources:
    requests:
      storage: 3Gi
