collections:
  - name: community.general
    # version: ">=7.0.0"
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: ">=1.16.3"
    source: https://galaxy.ansible.com
  - name: containers.podman.podman_network
    source: https://galaxy.ansible.com
