---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: rtsp0-udp-ir
  namespace: v4l2rtspserver
spec:
  entryPoints:
    - rtspudp
  routes:
  - services:
    - name: rtsp0-svc
      port: rtsp-svc-udp
      weight: 10
      nativeLB: true
