---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rtsp0-hls-ir
  namespace: v4l2rtspserver
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`rtsp0-hls.app.rick.expresso.lan`)
    kind: Rule
    priority: 30
    services:
    - kind: Service
      name: rtsp0-hls-svc
      namespace: v4l2rtspserver
      passHostHeader: true
      port: rtsp-hls-web
      responseForwarding:
        flushInterval: 1ms
      scheme: http
      sticky:
        cookie:
          httpOnly: true
          name: cookie
          secure: true
          sameSite: none
          maxAge: 42  
      strategy: RoundRobin
      weight: 40
      nativeLB: true
  tls: {}
