---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rtsp0-tcp-ir
  namespace: v4l2rtspserver
spec:
  entryPoints:
    - rtsptcp
  routes:
  - match: ClientIP(`10.50.0.0/24`)
    priority: 20
    services:
    - name: rtsp0-svc
      port: rtsp-svc-tcp
      serversTransport: transport-rtsp-tcp
      nativeLB: true
      tls: false
