---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-certificate
  namespace: default
spec:
  secretName: default-certificate
  dnsNames:
    - "app.rick.expresso.lan"
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
